common:
  app: tavlavis
  shortname: tavla-v
  team: selvbetjent
  env: dev
  ingress:
    enabled: true
    trafficType: public
  service:
    internalPort: 9000
  deployment:
    prometheus:
      enabled: true
    replicas: 2
  container:
    image: <+artifacts.primary.image>
    cpu: 0.3
    memory: 512

    probes:
      enabled: true
      spec:
        startupProbe:
          tcpSocket:
            port: 3000
          periodSeconds: 1
          timeoutSeconds: 1
          failureThreshold: 300
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 3000
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          tcpSocket:
            port: 3000
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
  configmap:
    enabled: true
    data:
      TZ: "Europe/Oslo"
  secrets:
    auth-credentials:
      - MNG_AUTH0_INT_CLIENT_ID
      - MNG_AUTH0_INT_CLIENT_SECRET
